---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/tkdchen/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-manage-registryredhatio-pull-secret-for-e2e
