---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/tkdchen/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-STONEBLD-1785-test-deploy-image-pruner-cronjob
