apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/tkdchen/mintmaker/config/default?ref=49dd9f0ab99dac13ab1b067de9c14abd1d134b47
  - https://github.com/tkdchen/mintmaker/config/renovate?ref=49dd9f0ab99dac13ab1b067de9c14abd1d134b47
images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/konflux-ci/mintmaker
    newTag: 7f0cd9e10e0ede8e2dcce8e5cbaa3647b4548cc4
namespace: mintmaker
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
components:
  - ../components/rh-certs
