apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - https://github.com/tkdchen/mintmaker/config/default?ref=de3d851e9aa4243c33dc3946027409d9fe1ad076
  - https://github.com/tkdchen/mintmaker/config/renovate?ref=de3d851e9aa4243c33dc3946027409d9fe1ad076
images:
  - name: quay.io/konflux-ci/mintmaker
    newName: quay.io/mytestworkload/mintmaker
    newTag: de3d851e9aa4243c33dc3946027409d9fe1ad076-2025-01-16T10_00_47-08_00
namespace: mintmaker
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
components:
  - ../components/rh-certs
