resources:
- allow-argocd-to-manage.yaml
- https://github.com/tkdchen/image-controller/config/default?ref=18408e7e96b89bb2c15aac0aefe251e28b56ab67
- rbac

images:
- name: quay.io/redhat-appstudio/image-controller
  newName: quay.io/redhat-appstudio/image-controller
  newTag: 8208ff372b880773b911062dc828f050e45c5312

namespace: image-controller

patches:
  - path: ./manager_resources_patch.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

