apiVersion: v1
kind: ServiceAccount
metadata:
  name: appstudio-pipeline
secrets:
  - name: quay-push-secret
  - name: registryredhatio-pull-secret
imagePullSecrets:
  - name: quay-push-secret
  - name: registryredhatio-pull-secret
